// <auto-generated />
using System;
using Domain.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Domain.Migrations
{
    [DbContext(typeof(BsMovieContext))]
    [Migration("20221119042601_SeedingDB")]
    partial class SeedingDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.Movies", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Cancelled")
                        .HasColumnType("bit");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cancelled = false,
                            Gender = "Fantasy",
                            Name = "Andalusian Dog, An (Chien andalou, Un)"
                        },
                        new
                        {
                            Id = 2,
                            Cancelled = false,
                            Gender = "Action|Adventure|Comedy|Romance|Thriller",
                            Name = "Lara Croft Tomb Raider: The Cradle of Life"
                        },
                        new
                        {
                            Id = 3,
                            Cancelled = false,
                            Gender = "Drama|Thriller",
                            Name = "Bottom of the Sea, The (El fondo del mar)"
                        },
                        new
                        {
                            Id = 4,
                            Cancelled = false,
                            Gender = "Comedy|Romance",
                            Name = "Auntie from Chicago, The (I theia apo to Chicago)"
                        },
                        new
                        {
                            Id = 5,
                            Cancelled = false,
                            Gender = "Action|Thriller",
                            Name = "Way of War, The"
                        },
                        new
                        {
                            Id = 6,
                            Cancelled = true,
                            Gender = "Thriller",
                            Name = "State Affairs (Une affaire d'état)"
                        },
                        new
                        {
                            Id = 7,
                            Cancelled = false,
                            Gender = "Drama",
                            Name = "Canvas"
                        },
                        new
                        {
                            Id = 8,
                            Cancelled = false,
                            Gender = "Drama|Romance",
                            Name = "Last Tycoon, The"
                        },
                        new
                        {
                            Id = 9,
                            Cancelled = false,
                            Gender = "Action|Sci-Fi",
                            Name = "King Kong vs. Godzilla (Kingukongu tai Gojira)"
                        },
                        new
                        {
                            Id = 10,
                            Cancelled = true,
                            Gender = "Action|Crime|Drama|Thriller",
                            Name = "Tesseract, The"
                        },
                        new
                        {
                            Id = 11,
                            Cancelled = false,
                            Gender = "Action|Romance",
                            Name = "Once Upon a Time in China II (Wong Fei-hung Ji Yi: Naam yi dong ji keung)"
                        },
                        new
                        {
                            Id = 12,
                            Cancelled = true,
                            Gender = "Comedy|Fantasy|Romance",
                            Name = "Topper"
                        },
                        new
                        {
                            Id = 13,
                            Cancelled = false,
                            Gender = "Comedy",
                            Name = "Spy Hard"
                        },
                        new
                        {
                            Id = 14,
                            Cancelled = false,
                            Gender = "Comedy|Musical",
                            Name = "Stand Up and Cheer!"
                        },
                        new
                        {
                            Id = 15,
                            Cancelled = false,
                            Gender = "Comedy|Thriller",
                            Name = "Helsinki Napoli All Night Long"
                        },
                        new
                        {
                            Id = 16,
                            Cancelled = true,
                            Gender = "Comedy",
                            Name = "The Pool Boys"
                        },
                        new
                        {
                            Id = 17,
                            Cancelled = true,
                            Gender = "Animation|Children|Comedy|Crime",
                            Name = "Wallace & Gromit: The Wrong Trousers"
                        },
                        new
                        {
                            Id = 18,
                            Cancelled = false,
                            Gender = "Comedy",
                            Name = "King of California"
                        },
                        new
                        {
                            Id = 19,
                            Cancelled = true,
                            Gender = "Drama|Thriller|War",
                            Name = "Thirteen Days"
                        },
                        new
                        {
                            Id = 20,
                            Cancelled = false,
                            Gender = "Horror|Thriller",
                            Name = "Hostel: Part III "
                        },
                        new
                        {
                            Id = 21,
                            Cancelled = false,
                            Gender = "Crime|Drama|Thriller",
                            Name = "The Rise"
                        },
                        new
                        {
                            Id = 22,
                            Cancelled = true,
                            Gender = "Drama",
                            Name = "Wife! Be Like a Rose! (Tsuma yo bara no yo ni)"
                        },
                        new
                        {
                            Id = 23,
                            Cancelled = true,
                            Gender = "Drama",
                            Name = "Horse Rebellion, The (Pulakapina)"
                        },
                        new
                        {
                            Id = 24,
                            Cancelled = true,
                            Gender = "Comedy|Crime|Mystery",
                            Name = "Curse of the Pink Panther"
                        },
                        new
                        {
                            Id = 25,
                            Cancelled = true,
                            Gender = "Drama",
                            Name = "Passionate Friends, The (a.k.a. One Woman's Story)"
                        },
                        new
                        {
                            Id = 26,
                            Cancelled = false,
                            Gender = "Drama|Romance|War",
                            Name = "Doctor Zhivago"
                        },
                        new
                        {
                            Id = 27,
                            Cancelled = false,
                            Gender = "Drama|Romance",
                            Name = "Elementary Particles, The (Elementarteilchen)"
                        },
                        new
                        {
                            Id = 28,
                            Cancelled = false,
                            Gender = "Adventure",
                            Name = "Buccaneer, The"
                        },
                        new
                        {
                            Id = 29,
                            Cancelled = true,
                            Gender = "Crime|Thriller",
                            Name = "Sudden Impact"
                        },
                        new
                        {
                            Id = 30,
                            Cancelled = true,
                            Gender = "Romance|Thriller",
                            Name = "Kill Me Later"
                        },
                        new
                        {
                            Id = 31,
                            Cancelled = true,
                            Gender = "Action|Sci-Fi",
                            Name = "King of Fighters, The"
                        },
                        new
                        {
                            Id = 32,
                            Cancelled = false,
                            Gender = "Comedy|Drama",
                            Name = "Woman, a Gun and a Noodle Shop, A (San qiang pai an jing qi)"
                        },
                        new
                        {
                            Id = 33,
                            Cancelled = false,
                            Gender = "Action",
                            Name = "Best of the Best 2"
                        },
                        new
                        {
                            Id = 34,
                            Cancelled = true,
                            Gender = "Action|Horror|Sci-Fi",
                            Name = "Doom"
                        },
                        new
                        {
                            Id = 35,
                            Cancelled = false,
                            Gender = "Adventure",
                            Name = "Brenda Starr"
                        },
                        new
                        {
                            Id = 36,
                            Cancelled = false,
                            Gender = "Comedy|Mystery",
                            Name = "Private Eyes, The"
                        },
                        new
                        {
                            Id = 37,
                            Cancelled = false,
                            Gender = "Animation|Children|Fantasy",
                            Name = "Care Bears Movie, The"
                        },
                        new
                        {
                            Id = 38,
                            Cancelled = true,
                            Gender = "Comedy",
                            Name = "First Wives Club, The"
                        },
                        new
                        {
                            Id = 39,
                            Cancelled = false,
                            Gender = "Drama",
                            Name = "Hot Saturday"
                        },
                        new
                        {
                            Id = 40,
                            Cancelled = false,
                            Gender = "Drama|War",
                            Name = "Ivan's Childhood (a.k.a. My Name is Ivan) (Ivanovo detstvo)"
                        },
                        new
                        {
                            Id = 41,
                            Cancelled = true,
                            Gender = "Action|Comedy|Crime|Thriller",
                            Name = "Ca$h"
                        },
                        new
                        {
                            Id = 42,
                            Cancelled = false,
                            Gender = "Drama",
                            Name = "Insect Woman, The (Nippon konchûki)"
                        },
                        new
                        {
                            Id = 43,
                            Cancelled = true,
                            Gender = "Drama",
                            Name = "Promised Life, The (Vie promise, La)"
                        },
                        new
                        {
                            Id = 44,
                            Cancelled = true,
                            Gender = "Adventure|Comedy|Fantasy|Romance|IMAX",
                            Name = "Journey to the West: Conquering the Demons (Daai wa sai you chi Chui mo chun kei)"
                        },
                        new
                        {
                            Id = 45,
                            Cancelled = true,
                            Gender = "Adventure|Drama|Fantasy",
                            Name = "Sophie's World (Sofies verden)"
                        },
                        new
                        {
                            Id = 46,
                            Cancelled = true,
                            Gender = "Horror",
                            Name = "ABCs of Death, The"
                        },
                        new
                        {
                            Id = 47,
                            Cancelled = false,
                            Gender = "Horror|Sci-Fi",
                            Name = "Frozen Dead, The"
                        },
                        new
                        {
                            Id = 48,
                            Cancelled = false,
                            Gender = "Comedy|Drama",
                            Name = "Linda Linda Linda"
                        },
                        new
                        {
                            Id = 49,
                            Cancelled = true,
                            Gender = "Comedy",
                            Name = "Garage, The"
                        },
                        new
                        {
                            Id = 50,
                            Cancelled = true,
                            Gender = "Comedy",
                            Name = "Owl and the Pussycat, The"
                        },
                        new
                        {
                            Id = 51,
                            Cancelled = true,
                            Gender = "Horror|Sci-Fi",
                            Name = "Carnosaur"
                        },
                        new
                        {
                            Id = 52,
                            Cancelled = false,
                            Gender = "Drama|Mystery|Thriller",
                            Name = "Turks & Caicos"
                        },
                        new
                        {
                            Id = 53,
                            Cancelled = false,
                            Gender = "Documentary",
                            Name = "Iran Is Not the Problem"
                        },
                        new
                        {
                            Id = 54,
                            Cancelled = true,
                            Gender = "Drama|Musical",
                            Name = "Stomp the Yard"
                        },
                        new
                        {
                            Id = 55,
                            Cancelled = true,
                            Gender = "Comedy|Horror|Thriller",
                            Name = "Housebound"
                        },
                        new
                        {
                            Id = 56,
                            Cancelled = true,
                            Gender = "Drama|Musical",
                            Name = "Georg"
                        },
                        new
                        {
                            Id = 57,
                            Cancelled = true,
                            Gender = "Action|Adventure|Drama",
                            Name = "Tomorrow, When the War Began"
                        },
                        new
                        {
                            Id = 58,
                            Cancelled = false,
                            Gender = "Drama",
                            Name = "Human Capital (Il capitale umano)"
                        },
                        new
                        {
                            Id = 59,
                            Cancelled = false,
                            Gender = "Crime|Drama|Romance",
                            Name = "Nordkraft"
                        },
                        new
                        {
                            Id = 60,
                            Cancelled = true,
                            Gender = "Drama|Romance",
                            Name = "Spread"
                        },
                        new
                        {
                            Id = 61,
                            Cancelled = false,
                            Gender = "Comedy",
                            Name = "Skin Deep"
                        },
                        new
                        {
                            Id = 62,
                            Cancelled = false,
                            Gender = "Comedy|Drama|Romance",
                            Name = "Postman, The (Postino, Il)"
                        },
                        new
                        {
                            Id = 63,
                            Cancelled = false,
                            Gender = "Drama",
                            Name = "From the Clouds to the Resistance (Dalla nube alla resistenza)"
                        },
                        new
                        {
                            Id = 64,
                            Cancelled = false,
                            Gender = "Action|Drama|Fantasy",
                            Name = "Promise, The (Wu ji)"
                        },
                        new
                        {
                            Id = 65,
                            Cancelled = true,
                            Gender = "Action",
                            Name = "Confessions of a Gangsta"
                        },
                        new
                        {
                            Id = 66,
                            Cancelled = true,
                            Gender = "Children|Musical",
                            Name = "Teen Beach Movie"
                        },
                        new
                        {
                            Id = 67,
                            Cancelled = true,
                            Gender = "Action|Thriller",
                            Name = "Point of No Return"
                        },
                        new
                        {
                            Id = 68,
                            Cancelled = true,
                            Gender = "Documentary",
                            Name = "Sam Peckinpah: Man of Iron"
                        },
                        new
                        {
                            Id = 69,
                            Cancelled = true,
                            Gender = "Drama|Fantasy|Romance",
                            Name = "Orlando"
                        },
                        new
                        {
                            Id = 70,
                            Cancelled = false,
                            Gender = "Comedy|Romance",
                            Name = "Black Coffee"
                        },
                        new
                        {
                            Id = 71,
                            Cancelled = false,
                            Gender = "Action|Drama|War",
                            Name = "Saints and Soldiers: Airborne Creed"
                        },
                        new
                        {
                            Id = 72,
                            Cancelled = false,
                            Gender = "Drama",
                            Name = "End of St. Petersburg, The (Konets Sankt-Peterburga)"
                        },
                        new
                        {
                            Id = 73,
                            Cancelled = true,
                            Gender = "Crime|Drama",
                            Name = "Johnny Handsome"
                        },
                        new
                        {
                            Id = 74,
                            Cancelled = false,
                            Gender = "Sci-Fi",
                            Name = "Noah's Arc Principle, The (Arche Noah Prinzip, Das)"
                        },
                        new
                        {
                            Id = 75,
                            Cancelled = false,
                            Gender = "Comedy",
                            Name = "HealtH"
                        },
                        new
                        {
                            Id = 76,
                            Cancelled = false,
                            Gender = "Drama|Romance",
                            Name = "Love and Basketball"
                        },
                        new
                        {
                            Id = 77,
                            Cancelled = true,
                            Gender = "Comedy|Drama",
                            Name = "All Together"
                        },
                        new
                        {
                            Id = 78,
                            Cancelled = false,
                            Gender = "Action|Crime",
                            Name = "Electra Glide in Blue"
                        },
                        new
                        {
                            Id = 79,
                            Cancelled = false,
                            Gender = "Comedy|Musical",
                            Name = "Adventures of Power"
                        },
                        new
                        {
                            Id = 80,
                            Cancelled = true,
                            Gender = "Action|Adventure|Fantasy|IMAX",
                            Name = "Oz the Great and Powerful"
                        },
                        new
                        {
                            Id = 81,
                            Cancelled = true,
                            Gender = "Documentary",
                            Name = "Armstrong Lie, The"
                        },
                        new
                        {
                            Id = 82,
                            Cancelled = false,
                            Gender = "Drama|War",
                            Name = "Nicholas and Alexandra"
                        },
                        new
                        {
                            Id = 83,
                            Cancelled = false,
                            Gender = "Comedy",
                            Name = "Page Miss Glory"
                        },
                        new
                        {
                            Id = 84,
                            Cancelled = false,
                            Gender = "Documentary",
                            Name = "Manufactured Landscapes"
                        },
                        new
                        {
                            Id = 85,
                            Cancelled = true,
                            Gender = "Documentary",
                            Name = "English Surgeon, The"
                        },
                        new
                        {
                            Id = 86,
                            Cancelled = true,
                            Gender = "Drama|Fantasy",
                            Name = "Magic Sword, The"
                        },
                        new
                        {
                            Id = 87,
                            Cancelled = true,
                            Gender = "Comedy|Drama",
                            Name = "Color of Friendship, The"
                        },
                        new
                        {
                            Id = 88,
                            Cancelled = false,
                            Gender = "Drama",
                            Name = "Hotel New Hampshire, The"
                        },
                        new
                        {
                            Id = 89,
                            Cancelled = true,
                            Gender = "Comedy",
                            Name = "Yolki 2"
                        },
                        new
                        {
                            Id = 90,
                            Cancelled = false,
                            Gender = "Crime|Drama|Film-Noir|Mystery|Thriller",
                            Name = "Mulholland Drive"
                        },
                        new
                        {
                            Id = 91,
                            Cancelled = false,
                            Gender = "Action|Drama",
                            Name = "Zatoichi's Vengeance (Zatôichi no uta ga kikoeru) (Zatôichi 13)"
                        },
                        new
                        {
                            Id = 92,
                            Cancelled = true,
                            Gender = "Comedy",
                            Name = "Louis C.K.: Live at The Comedy Store"
                        },
                        new
                        {
                            Id = 93,
                            Cancelled = false,
                            Gender = "Drama|Thriller",
                            Name = "Debt, The"
                        },
                        new
                        {
                            Id = 94,
                            Cancelled = true,
                            Gender = "Drama",
                            Name = "The Puzzle"
                        },
                        new
                        {
                            Id = 95,
                            Cancelled = false,
                            Gender = "Documentary",
                            Name = "McCullin"
                        },
                        new
                        {
                            Id = 96,
                            Cancelled = true,
                            Gender = "(no genres listed)",
                            Name = "Istanbul"
                        },
                        new
                        {
                            Id = 97,
                            Cancelled = false,
                            Gender = "Action|Adventure",
                            Name = "36th Chamber of Shaolin, The (Shao Lin san shi liu fang) (Master Killer)"
                        },
                        new
                        {
                            Id = 98,
                            Cancelled = true,
                            Gender = "Comedy|Drama",
                            Name = "Daddy and Them"
                        },
                        new
                        {
                            Id = 99,
                            Cancelled = false,
                            Gender = "Horror",
                            Name = "Prowler, The (a.k.a. Rosemary's Killer) (a.k.a. The Graduation)"
                        },
                        new
                        {
                            Id = 100,
                            Cancelled = true,
                            Gender = "Drama",
                            Name = "Warped Ones, The (Kyonetsu no kisetsu)"
                        });
                });

            modelBuilder.Entity("Domain.Models.Reviews", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Cancelled")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<string>("Review")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
